version: "3.3"

services:
  openai_bot:
    container_name: openai_bot
    environment:
      - WEBEX_TEAMS_ACCESS_TOKEN
      - LOG_LEVEL
    image: openai_bot
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER
      - REPO_PASS
    command: --interval 60 openai_bot
